base:
  config: "configs/fairl/fairl_cfg.yaml"
  control: "fairl"
  randomize: ""
  size: 10
  maze: "big"
  headless: True
  H: 70
  num_expert_samples: 1
  network: "fc"
  save_dir: "fairl_fc_none"
fairl:
  num_train_samples: 1
  num_test_samples: 1
  num_eval_runs: 1
  num_epochs: 500
  batch_size: 600
  learning_rate: 0.001
  save_weights: True
  eval_freq: 50
eval:
  num_eval_samples: 50
