base:
  config: "configs/bc/bc_exp_cfg.yaml"
  control: "bc-al"
  save_dir: "bc-al-big-map-new/random_2"
  randomize: "g"
  maze: "big"
  size: None
  network: "fc"
  headless: True
  H: 100
  num_expert_samples: 50
bc:
  num_train_samples: 100
  num_test_samples: 100
  num_eval_runs: 50
  #num_epochs: 5000
  num_epochs: 2000
  batch_size: 32
  learning_rate: 0.001
  save_weights: True
  eval_freq: None
al:
  # Heurstic can be "gam", "gm", "ed", "random"
  heuristic: "random"
  acquisition_func_name: "failed_min_max"
  batch_size: 5
eval:
  num_eval_samples: 200